import Head from "next/head";
import { Montserrat } from "next/font/google";
import JPLogo from "./JPLogo";
import LinearGradient from "./LinearGradient";
import MovingBlobs from "./MovingBlobs";
import styles from "@/styles/Home.module.css";
import { gradientStop } from "@/types/gradientStop";


const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['500']
});

export default function Home() {
  
  const svgSize = {width: 840, height: 203};
  const gradientStops: gradientStop[] = [
    {offset: 30, minOffset: 0, maxOffset: 40, lastTurn: 0, dir: 1, color: 'magenta'},
    {offset: 60, minOffset: 20, maxOffset: 80, lastTurn: 0, dir: 1, color: 'cyan'},
    {offset: 100, minOffset: 90, maxOffset: 100, lastTurn: 0, dir: 1, color: 'hsl(270, 100%, 50%)'}
  ];
  const blobs = [
    {
      x: 0,
      y: 0,
      angle: -Math.PI/4,
      color: 'red',
      width: 500,
      height: 250
    },
    {
      x: 0,
      y: 0,
      angle: -Math.PI,
      color: 'yellow',
      width: 750,
      height: 500
    },
    {
      x: 0,
      y: 0,
      angle: -2*Math.PI/3,
      color: 'orange',
      width: 1000,
      height: 1000
    }
  ];

  return (
    <>
      <Head>
        <title>Text Gradient Animation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <svg viewBox={`0 0 ${svgSize.width} ${svgSize.height}`} className={styles.svg}>
            <defs>
              <mask id="mask" className={styles.text}>
                <JPLogo /> 
                <g className={montserrat.className}>
                  <text x="220" y="90">Johanna</text>
                  <text x="210" y="200">Palmkvist</text>
                </g>
              </mask>
            </defs>
            <g mask="url(#mask)">
              <LinearGradient initStops={gradientStops} speed={0.001} svgSize={svgSize} />
              {blobs.map((blob, i) => <MovingBlobs key={i} id={'blob'+i} x={blob.x} y={blob.y} angle={blob.angle} color={blob.color} speed={2} width={blob.width} height={blob.height} svgSize={svgSize} />)}
            </g>
        </svg>
      </div>
    </>
  );
}
